<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key' => 'group_mwm_section_01',
			'title' => 'MWM Section 01',
			'fields' => array(
				array(
					'key' => 'field_mwm_section_01_position_media',
					'label' => 'Posición del media',
					'name' => 'position_media',
					'type' => 'select',
					'instructions' => 'Selecciona la posición del bloque de media (imagen).',
					'required' => 0,
					'choices' => array(
						'left' => 'Media izquierda',
						'right' => 'Media derecha',
						'center-top' => 'Media arriba (centrado)',
						'center-bottom' => 'Media abajo (centrado)',
					),
					'default_value' => 'left',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
				),
				array(
					'key' => 'field_mwm_section_01_background_outline',
					'label' => 'Fondo / borde',
					'name' => 'background_outline',
					'type' => 'select',
					'instructions' => 'Selecciona el estilo de fondo y/o borde de la sección.',
					'required' => 0,
					'choices' => array(
						'none-none' => 'Sin fondo / sin borde',
						'white-none' => 'Fondo blanco / sin borde',
						'grey' => 'Fondo gris / sin borde',
						'border-grey' => 'Fondo gris / con borde gris',
						'none-blue' => 'Sin fondo / borde azul (para fondos oscuros)',
						'blue-none' => 'Fondo azul / sin borde',
					),
					'default_value' => 'none-none',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
				),
				array(
					'key' => 'field_mwm_section_01_color_text',
					'label' => 'Color del texto',
					'name' => 'color_text',
					'type' => 'select',
					'instructions' => 'Selecciona el color del texto principal.',
					'required' => 0,
					'choices' => array(
						'blue' => 'Azul',
						'white' => 'Blanco',
					),
					'default_value' => 'blue',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
				),
				array(
					'key' => 'field_mwm_section_01_show_media',
					'label' => 'Mostrar media',
					'name' => 'show_media',
					'type' => 'true_false',
					'instructions' => 'Activa o desactiva el bloque de media.',
					'required' => 0,
					'default_value' => 1,
					'ui' => 1,
				),
				array(
					'key' => 'field_mwm_section_01_media_type',
					'label' => 'Tipo de media',
					'name' => 'media_type',
					'type' => 'select',
					'instructions' => __( 'Selecciona si quieres usar video o imagen.', 'bilky' ),
					'required' => 0,
					'choices' => array(
						'image' => __( 'Imagen', 'bilky' ),
						'video' => __( 'Video', 'bilky' ),
					),
					'default_value' => 'image',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_mwm_section_01_show_media',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
				),
				array(
					'key' => 'field_mwm_section_01_media_image',
					'label' => 'Imagen',
					'name' => 'media_image',
					'type' => 'image',
					'instructions' => __( 'Sube una imagen, si se deja vacío se mostrará un placeholder', 'bilky' ),
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_mwm_section_01_show_media',
								'operator' => '==',
								'value' => '1',
							),
							array(
								'field' => 'field_mwm_section_01_media_type',
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'return_format' => 'ID',
					'preview_size' => 'medium',
					'library' => 'all',
				),
				array(
					'key' => 'field_mwm_section_01_media_video',
					'label' => 'Video',
					'name' => 'media_video',
					'type' => 'file',
					'instructions' => __( 'Sube un archivo de video. El video se reproducirá automáticamente, sin sonido y en bucle.', 'bilky' ),
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_mwm_section_01_show_media',
								'operator' => '==',
								'value' => '1',
							),
							array(
								'field' => 'field_mwm_section_01_media_type',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => 'mp4,webm,ogg',
				),
				array(
					'key' => 'field_mwm_section_01_show_badge',
					'label' => 'Mostrar botón superior (badge)',
					'name' => 'show_badge',
					'type' => 'true_false',
					'instructions' => 'Activa o desactiva el botón superior tipo badge.',
					'required' => 0,
					'default_value' => 1,
					'ui' => 1,
				),
				array(
					'key' => 'field_mwm_section_01_badge_text',
					'label' => 'Texto del badge',
					'name' => 'badge_text',
					'type' => 'text',
					'instructions' => 'Texto del botón outline superior.',
					'required' => 0,
					'default_value' => 'Button',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_mwm_section_01_show_badge',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
				),
				array(
					'key' => 'field_mwm_section_01_badge_url',
					'label' => 'URL del badge',
					'name' => 'badge_url',
					'type' => 'text',
					'instructions' => 'URL del botón superior (si se deja vacío se renderiza como botón).',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_mwm_section_01_show_badge',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
				),
				array(
					'key' => 'field_mwm_section_01_show_icon',
					'label' => 'Mostrar icono',
					'name' => 'show_icon',
					'type' => 'true_false',
					'instructions' => 'Activa o desactiva el icono circular junto al título.',
					'required' => 0,
					'default_value' => 1,
					'ui' => 1,
				),
				array(
					'key' => 'field_mwm_section_01_icon',
					'label' => 'Icono',
					'name' => 'icon',
					'type' => 'text',
					'instructions' => 'Nombre del icono de Font Awesome 7 Pro (ej: briefcase).',
					'required' => 0,
					'default_value' => 'briefcase',
					'placeholder' => 'briefcase',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_mwm_section_01_show_icon',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
				),
				array(
					'key' => 'field_mwm_section_01_icon_color',
					'label' => 'Color del icono',
					'name' => 'icon_color',
					'type' => 'select',
					'instructions' => __( 'Selecciona el color del icono del título.', 'bilky' ),
					'required' => 0,
					'choices' => array(
						'grey' => __( 'Gris', 'bilky' ),
						'green' => __( 'Verde', 'bilky' ),
					),
					'default_value' => 'grey',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_mwm_section_01_show_icon',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
				),
				array(
					'key' => 'field_mwm_section_01_title',
					'label' => 'Título',
					'name' => 'title',
					'type' => 'text',
					'instructions' => 'Título principal.',
					'required' => 0,
					'default_value' => '¿Cómo funciona Bilky?',
				),
				array(
					'key' => 'field_mwm_section_01_show_description_opacity',
					'label' => 'Descripción con opacidad 100%',
					'name' => 'show_description_opacity',
					'type' => 'true_false',
					'instructions' => 'Activa para mostrar la descripción con opacidad 100%.',
					'required' => 0,
					'default_value' => 0,
					'ui' => 1,
				),
				array(
					'key' => 'field_mwm_section_01_description',
					'label' => 'Descripción',
					'name' => 'description',
					'type' => 'wysiwyg',
					'instructions' => 'Texto descriptivo.',
					'required' => 0,
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
					'default_value' => 'Bilky es una plataforma digital que une todos tus procesos —facturación, documentos, comunicación y RRHH— en portales conectados entre sí, para que asesorías, empresas y empleados trabajen siempre alineados.',
				),
				array(
					'key' => 'field_mwm_section_01_show_list',
					'label' => 'Mostrar lista',
					'name' => 'show_list',
					'type' => 'true_false',
					'instructions' => 'Activa o desactiva la lista de elementos.',
					'required' => 0,
					'default_value' => 1,
					'ui' => 1,
				),
				array(
					'key' => 'field_mwm_section_01_list_style',
					'label' => 'Estilo de lista',
					'name' => 'list_style',
					'type' => 'select',
					'instructions' => 'Por defecto se calcula automáticamente según la variante. Puedes forzarlo aquí.',
					'required' => 0,
					'choices' => array(
						'auto' => 'Automático',
						'grey-blue' => 'Card gris (grey-blue)',
						'white-blue' => 'Card blanca (white-blue)',
						'none' => 'Sin fondo (none)',
					),
					'default_value' => 'auto',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_mwm_section_01_show_list',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
				),
				array(
					'key' => 'field_mwm_section_01_list_icon_color',
					'label' => 'Color del icono de la lista',
					'name' => 'list_icon_color',
					'type' => 'select',
					'instructions' => __( 'Selecciona el color de los iconos de la lista.', 'bilky' ),
					'required' => 0,
					'choices' => array(
						'green' => __( 'Verde', 'bilky' ),
						'blue' => __( 'Azul', 'bilky' ),
					),
					'default_value' => 'green',
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_mwm_section_01_show_list',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
				),
				array(
					'key' => 'field_mwm_section_01_list_items',
					'label' => 'Elementos de la lista',
					'name' => 'list_items',
					'type' => 'repeater',
					'instructions' => 'Añade los elementos de la lista.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_mwm_section_01_show_list',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_mwm_section_01_list_item_text',
					'min' => 1,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Añadir elemento',
					'sub_fields' => array(
						array(
							'key' => 'field_mwm_section_01_list_item_text',
							'label' => 'Texto',
							'name' => 'text',
							'type' => 'text',
							'instructions' => 'Texto principal del item.',
							'required' => 0,
						),
						array(
							'key' => 'field_mwm_section_01_list_item_icon',
							'label' => 'Icono',
							'name' => 'icon',
							'type' => 'text',
							'instructions' => __( 'Nombre del icono de Font Awesome 7 Pro (ej: circle-check, check, star, etc.).', 'bilky' ),
							'required' => 0,
							'default_value' => 'circle-check',
							'placeholder' => 'circle-check',
						),
					),
				),
				array(
					'key' => 'field_mwm_section_01_show_button',
					'label' => 'Mostrar botón inferior',
					'name' => 'show_button',
					'type' => 'true_false',
					'instructions' => 'Activa o desactiva el botón inferior.',
					'required' => 0,
					'default_value' => 1,
					'ui' => 1,
				),
				array(
					'key' => 'field_mwm_section_01_button_text',
					'label' => 'Texto del botón',
					'name' => 'button_text',
					'type' => 'text',
					'instructions' => 'Texto del botón inferior.',
					'required' => 0,
					'default_value' => 'Button',
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_mwm_section_01_show_button',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
				),
				array(
					'key' => 'field_mwm_section_01_button_url',
					'label' => 'URL del botón',
					'name' => 'button_url',
					'type' => 'text',
					'instructions' => 'URL del botón inferior (si se deja vacío se renderiza como botón).',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_mwm_section_01_show_button',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/mwm-section-01',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
		)
	);

endif;

