<?php

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_mwm_section_17',
			'title'                 => __( 'MWM Section 17', 'bilky' ),
			'fields'                => array(
				// Header - Breadcrumb
				array(
					'key'               => 'field_mwm_section_17_breadcrumb_01_text',
					'label'             => __( 'Texto Breadcrumb', 'bilky' ),
					'name'              => 'breadcrumb_01_text',
					'type'              => 'text',
					'instructions'      => __( 'Texto del primer breadcrumb', 'bilky' ),
					'required'          => 0,
				),
				// Header - Título
				array(
					'key'               => 'field_mwm_section_17_title',
					'label'             => __( 'Título', 'bilky' ),
					'name'              => 'title',
					'type'              => 'textarea',
					'instructions'      => __( 'Título principal (se puede dividir en líneas)', 'bilky' ),
					'required'          => 0,
					'rows'              => 3,
				),
				// Header - Text Body
				array(
					'key'               => 'field_mwm_section_17_show_text_body',
					'label'             => __( 'Mostrar texto del cuerpo', 'bilky' ),
					'name'              => 'show_text_body',
					'type'              => 'true_false',
					'instructions'      => __( 'Activa o desactiva el texto descriptivo', 'bilky' ),
					'required'          => 0,
					'default_value'     => 0,
					'ui'                => 1,
				),
				array(
					'key'               => 'field_mwm_section_17_text_body',
					'label'             => __( 'Texto del cuerpo', 'bilky' ),
					'name'              => 'text_body',
					'type'              => 'wysiwyg',
					'instructions'      => __( 'Texto descriptivo que aparece debajo del título', 'bilky' ),
					'required'          => 0,
					'rows'              => 4,
					'toolbar'           => 'basic',
					'media_upload'      => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_mwm_section_17_show_text_body',
								'operator' => '==',
								'value'    => '1',
							),
						),
					),
				),
				// Layout selector
				array(
					'key'               => 'field_mwm_section_17_layout',
					'label'             => __( 'Layout', 'bilky' ),
					'name'              => 'layout',
					'type'              => 'select',
					'instructions'      => __( 'Selecciona el tipo de layout para las cards', 'bilky' ),
					'required'          => 0,
					'choices'           => array(
						'normal' => __( 'Normal', 'bilky' ),
						'tabs'   => __( 'Tabs', 'bilky' ),
					),
					'default_value'     => 'normal',
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 1,
					'ajax'              => 0,
					'return_format'     => 'value',
				),
				// Cards para layout normal
				array(
					'key'               => 'field_mwm_section_17_cards',
					'label'             => __( 'Cards', 'bilky' ),
					'name'              => 'cards',
					'type'              => 'repeater',
					'instructions'      => __( 'Añade las cards que quieras', 'bilky' ),
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_mwm_section_17_layout',
								'operator' => '==',
								'value'    => 'normal',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'          => 'field_mwm_section_17_card_title',
					'min'                => 0,
					'max'                => 0,
					'layout'             => 'block',
					'button_label'       => __( 'Añadir Card', 'bilky' ),
					'sub_fields'         => array(
						array(
							'key'               => 'field_mwm_section_17_card_background',
							'label'             => __( 'Fondo', 'bilky' ),
							'name'              => 'background',
							'type'              => 'select',
							'instructions'      => __( 'Selecciona el color de fondo de la card', 'bilky' ),
							'required'          => 0,
							'choices'           => array(
								'grey' => __( 'Fondo gris', 'bilky' ),
								'blue' => __( 'Fondo azul', 'bilky' ),
							),
							'default_value'     => 'grey',
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 1,
							'ajax'              => 0,
							'return_format'     => 'value',
						),
						array(
							'key'               => 'field_mwm_section_17_card_tag_text',
							'label'             => __( 'Tag texto', 'bilky' ),
							'name'              => 'tag_text',
							'type'              => 'text',
							'instructions'      => __( 'Texto del tag', 'bilky' ),
							'required'          => 0,
							'default_value'     => '',
							'placeholder'       => '',
						),
						array(
							'key'               => 'field_mwm_section_17_card_title',
							'label'             => __( 'Título', 'bilky' ),
							'name'              => 'title',
							'type'              => 'text',
							'instructions'      => __( 'Título de la card', 'bilky' ),
							'required'          => 0,
						),
						array(
							'key'               => 'field_mwm_section_17_card_description',
							'label'             => __( 'Descripción', 'bilky' ),
							'name'              => 'description',
							'type'              => 'textarea',
							'instructions'      => __( 'Texto descriptivo debajo del título de la card', 'bilky' ),
							'required'          => 0,
							'rows'              => 4,
							'new_lines'         => '',
						),
						array(
							'key'               => 'field_mwm_section_17_card_show_list',
							'label'             => __( 'Mostrar lista', 'bilky' ),
							'name'              => 'show_list',
							'type'              => 'true_false',
							'instructions'      => __( 'Activa o desactiva la lista de elementos', 'bilky' ),
							'required'          => 0,
							'default_value'     => 0,
							'ui'                => 1,
						),
						array(
							'key'               => 'field_mwm_section_17_card_list_items',
							'label'             => __( 'Elementos de la lista', 'bilky' ),
							'name'              => 'list_items',
							'type'              => 'repeater',
							'instructions'      => __( 'Añade los elementos de la lista', 'bilky' ),
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_mwm_section_17_card_show_list',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'          => 'field_mwm_section_17_card_list_item_text',
							'min'                => 1,
							'max'                => 0,
							'layout'             => 'block',
							'button_label'       => __( 'Añadir elemento', 'bilky' ),
							'sub_fields'         => array(
								array(
									'key'        => 'field_mwm_section_17_card_list_item_text',
									'label'      => __( 'Texto', 'bilky' ),
									'name'       => 'text',
									'type'       => 'text',
									'instructions' => __( 'Texto principal del item', 'bilky' ),
									'required'   => 0,
								),
							),
						),
						array(
							'key'               => 'field_mwm_section_17_card_show_button',
							'label'             => __( 'Mostrar botón', 'bilky' ),
							'name'              => 'show_button',
							'type'              => 'true_false',
							'instructions'      => __( 'Activa o desactiva el botón inferior', 'bilky' ),
							'required'          => 0,
							'default_value'     => 0,
							'ui'                => 1,
						),
						array(
							'key'               => 'field_mwm_section_17_card_button_text',
							'label'             => __( 'Texto del botón', 'bilky' ),
							'name'              => 'button_text',
							'type'              => 'text',
							'instructions'      => __( 'Texto del botón inferior', 'bilky' ),
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_mwm_section_17_card_show_button',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
						),
						array(
							'key'               => 'field_mwm_section_17_card_button_url',
							'label'             => __( 'URL del botón', 'bilky' ),
							'name'              => 'button_url',
							'type'              => 'text',
							'instructions'      => __( 'URL del botón inferior (si se deja vacío se renderiza como botón)', 'bilky' ),
							'required'          => 0,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_mwm_section_17_card_show_button',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
						),
					),
				),
				// Tabs para layout tabs
				array(
					'key'               => 'field_mwm_section_17_tabs',
					'label'             => __( 'Tabs', 'bilky' ),
					'name'              => 'tabs',
					'type'              => 'repeater',
					'instructions'      => __( 'Añade las tabs que quieras', 'bilky' ),
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_mwm_section_17_layout',
								'operator' => '==',
								'value'    => 'tabs',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'          => 'field_mwm_section_17_tab_title',
					'min'                => 1,
					'max'                => 0,
					'layout'             => 'block',
					'button_label'       => __( 'Añadir Tab', 'bilky' ),
					'sub_fields'         => array(
						array(
							'key'               => 'field_mwm_section_17_tab_title',
							'label'             => __( 'Título de la Tab', 'bilky' ),
							'name'              => 'tab_title',
							'type'              => 'text',
							'instructions'      => __( 'Título que aparecerá en la tab', 'bilky' ),
							'required'          => 1,
						),
						array(
							'key'               => 'field_mwm_section_17_tab_cards',
							'label'             => __( 'Cards de la Tab', 'bilky' ),
							'name'              => 'tab_cards',
							'type'              => 'repeater',
							'instructions'      => __( 'Añade las cards para esta tab', 'bilky' ),
							'required'          => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'collapsed'          => 'field_mwm_section_17_tab_card_title',
							'min'                => 0,
							'max'                => 0,
							'layout'             => 'block',
							'button_label'       => __( 'Añadir Card', 'bilky' ),
							'sub_fields'         => array(
								array(
									'key'               => 'field_mwm_section_17_tab_card_background',
									'label'             => __( 'Fondo', 'bilky' ),
									'name'              => 'background',
									'type'              => 'select',
									'instructions'      => __( 'Selecciona el color de fondo de la card', 'bilky' ),
									'required'          => 0,
									'choices'           => array(
										'grey' => __( 'Fondo gris', 'bilky' ),
										'blue' => __( 'Fondo azul', 'bilky' ),
									),
									'default_value'     => 'grey',
									'allow_null'        => 0,
									'multiple'          => 0,
									'ui'                => 1,
									'ajax'              => 0,
									'return_format'     => 'value',
								),
								array(
									'key'               => 'field_mwm_section_17_tab_card_tag_text',
									'label'             => __( 'Tag texto', 'bilky' ),
									'name'              => 'tag_text',
									'type'              => 'text',
									'instructions'      => __( 'Texto del tag', 'bilky' ),
									'required'          => 0,
									'default_value'     => '',
									'placeholder'       => '',
								),
								array(
									'key'               => 'field_mwm_section_17_tab_card_title',
									'label'             => __( 'Título', 'bilky' ),
									'name'              => 'title',
									'type'              => 'text',
									'instructions'      => __( 'Título de la card', 'bilky' ),
									'required'          => 0,
								),
								array(
									'key'               => 'field_mwm_section_17_tab_card_description',
									'label'             => __( 'Descripción', 'bilky' ),
									'name'              => 'description',
									'type'              => 'textarea',
									'instructions'      => __( 'Texto descriptivo debajo del título de la card', 'bilky' ),
									'required'          => 0,
									'rows'              => 4,
									'new_lines'         => '',
								),
								array(
									'key'               => 'field_mwm_section_17_tab_card_show_list',
									'label'             => __( 'Mostrar lista', 'bilky' ),
									'name'              => 'show_list',
									'type'              => 'true_false',
									'instructions'      => __( 'Activa o desactiva la lista de elementos', 'bilky' ),
									'required'          => 0,
									'default_value'     => 0,
									'ui'                => 1,
								),
								array(
									'key'               => 'field_mwm_section_17_tab_card_list_items',
									'label'             => __( 'Elementos de la lista', 'bilky' ),
									'name'              => 'list_items',
									'type'              => 'repeater',
									'instructions'      => __( 'Añade los elementos de la lista', 'bilky' ),
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_mwm_section_17_tab_card_show_list',
												'operator' => '==',
												'value'    => '1',
											),
										),
									),
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'          => 'field_mwm_section_17_tab_card_list_item_text',
									'min'                => 1,
									'max'                => 0,
									'layout'             => 'block',
									'button_label'       => __( 'Añadir elemento', 'bilky' ),
									'sub_fields'         => array(
										array(
											'key'        => 'field_mwm_section_17_tab_card_list_item_text',
											'label'      => __( 'Texto', 'bilky' ),
											'name'       => 'text',
											'type'       => 'text',
											'instructions' => __( 'Texto principal del item', 'bilky' ),
											'required'   => 0,
										),
									),
								),
								array(
									'key'               => 'field_mwm_section_17_tab_card_show_button',
									'label'             => __( 'Mostrar botón', 'bilky' ),
									'name'              => 'show_button',
									'type'              => 'true_false',
									'instructions'      => __( 'Activa o desactiva el botón inferior', 'bilky' ),
									'required'          => 0,
									'default_value'     => 0,
									'ui'                => 1,
								),
								array(
									'key'               => 'field_mwm_section_17_tab_card_button_text',
									'label'             => __( 'Texto del botón', 'bilky' ),
									'name'              => 'button_text',
									'type'              => 'text',
									'instructions'      => __( 'Texto del botón inferior', 'bilky' ),
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_mwm_section_17_tab_card_show_button',
												'operator' => '==',
												'value'    => '1',
											),
										),
									),
								),
								array(
									'key'               => 'field_mwm_section_17_tab_card_button_url',
									'label'             => __( 'URL del botón', 'bilky' ),
									'name'              => 'button_url',
									'type'              => 'text',
									'instructions'      => __( 'URL del botón inferior (si se deja vacío se renderiza como botón)', 'bilky' ),
									'required'          => 0,
									'conditional_logic' => array(
										array(
											array(
												'field'    => 'field_mwm_section_17_tab_card_show_button',
												'operator' => '==',
												'value'    => '1',
											),
										),
									),
								),
							),
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/mwm-section-17',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
		)
	);

endif;

