<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_mwm_section_03',
    'title' => 'MWM Section 03',
    'fields' => array(
        array(
            'key' => 'field_mwm_section_03_background',
            'label' => 'Color de fondo',
            'name' => 'background',
            'type' => 'select',
            'instructions' => 'Selecciona el color de fondo de la sección',
            'required' => 0,
            'choices' => array(
                'transparent' => 'Transparente',
                'white' => 'Blanco',
            ),
            'default_value' => 'transparent',
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
        ),
        array(
            'key' => 'field_mwm_section_03_position_media',
            'label' => 'Posición del media',
            'name' => 'position_media',
            'type' => 'select',
            'instructions' => 'Selecciona la posición del video/imagen',
            'required' => 0,
            'choices' => array(
                'left' => 'Izquierda',
                'right' => 'Derecha',
                'none' => 'Sin media',
            ),
            'default_value' => 'left',
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
        ),
        array(
            'key' => 'field_mwm_section_03_media_type',
            'label' => 'Tipo de media',
            'name' => 'media_type',
            'type' => 'select',
            'instructions' => 'Selecciona si quieres usar video o imagen',
            'required' => 0,
            'choices' => array(
                'video' => 'Video',
                'image' => 'Imagen',
            ),
            'default_value' => 'image',
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_mwm_section_03_position_media',
                        'operator' => '!=',
                        'value' => 'none',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_mwm_section_03_video',
            'label' => 'Video',
            'name' => 'video',
            'type' => 'file',
            'instructions' => 'Sube un archivo de video',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_mwm_section_03_position_media',
                        'operator' => '!=',
                        'value' => 'none',
                    ),
                    array(
                        'field' => 'field_mwm_section_03_media_type',
                        'operator' => '==',
                        'value' => 'video',
                    ),
                ),
            ),
            'return_format' => 'url',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => 'mp4,webm,ogg',
        ),
        array(
            'key' => 'field_mwm_section_03_image',
            'label' => 'Imagen',
            'name' => 'image',
            'type' => 'image',
            'instructions' => 'Sube una imagen',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_mwm_section_03_position_media',
                        'operator' => '!=',
                        'value' => 'none',
                    ),
                    array(
                        'field' => 'field_mwm_section_03_media_type',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                ),
            ),
            'return_format' => 'ID',
            'preview_size' => 'medium',
            'library' => 'all',
        ),
        array(
            'key' => 'field_mwm_section_03_show_icon',
            'label' => 'Mostrar icono',
            'name' => 'show_icon',
            'type' => 'true_false',
            'instructions' => 'Activa o desactiva el icono junto al título',
            'required' => 0,
            'default_value' => 1,
            'ui' => 1,
        ),
        array(
            'key' => 'field_mwm_section_03_icon',
            'label' => 'Icono',
            'name' => 'icon',
            'type' => 'text',
            'instructions' => 'Nombre del icono de Font Awesome 7 Pro (ej: briefcase, wifi, etc.)',
            'required' => 0,
            'default_value' => 'briefcase',
            'placeholder' => 'briefcase',
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_mwm_section_03_show_icon',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_mwm_section_03_title',
            'label' => 'Título',
            'name' => 'title',
            'type' => 'textarea',
            'instructions' => 'Título principal. Puedes usar saltos de línea para dividir en múltiples líneas',
            'required' => 0,
            'rows' => 3,
        ),
        array(
            'key' => 'field_mwm_section_03_show_text',
            'label' => 'Mostrar descripción',
            'name' => 'show_text',
            'type' => 'true_false',
            'instructions' => 'Activa o desactiva el texto descriptivo',
            'required' => 0,
            'default_value' => 1,
            'ui' => 1,
        ),
        array(
            'key' => 'field_mwm_section_03_text',
            'label' => 'Descripción',
            'name' => 'text',
            'type' => 'textarea',
            'instructions' => 'Texto descriptivo opcional',
            'required' => 0,
            'rows' => 4,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_mwm_section_03_show_text',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
        ),
        array(
            'key' => 'field_mwm_section_03_stats',
            'label' => 'Estadísticas',
            'name' => 'stats',
            'type' => 'repeater',
            'instructions' => 'Añade las cards de estadísticas (máximo 4). La última será verde por defecto',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_mwm_section_03_stat_percentage',
            'min' => 1,
            'max' => 4,
            'layout' => 'table',
            'button_label' => 'Añadir Estadística',
            'sub_fields' => array(
                array(
                    'key' => 'field_mwm_section_03_stat_percentage',
                    'label' => 'Porcentaje',
                    'name' => 'percentage',
                    'type' => 'text',
                    'instructions' => 'Porcentaje o número (ej: +80%, 100%, etc.)',
                    'required' => 0,
                    'default_value' => '+80%',
                ),
                array(
                    'key' => 'field_mwm_section_03_stat_description',
                    'label' => 'Descripción',
                    'name' => 'description',
                    'type' => 'textarea',
                    'instructions' => 'Descripción de la estadística. Puedes usar saltos de línea',
                    'required' => 0,
                    'rows' => 2,
                ),
                array(
                    'key' => 'field_mwm_section_03_stat_color',
                    'label' => 'Color de fondo',
                    'name' => 'color',
                    'type' => 'select',
                    'instructions' => 'Color de fondo de la card',
                    'required' => 0,
                    'choices' => array(
                        'grey' => 'Gris',
                        'green' => 'Verde',
                    ),
                    'default_value' => 'grey',
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/mwm-section-03',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

endif;

